name: 'OBS Studio Portable'

on:
  workflow_dispatch:
  # schedule:
    # - cron:  '0 1 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Release
        shell: bash
        run: |
          RELEASE=obs-studio-portable
          
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "RELEASETAG=23365" >> $GITHUB_ENV
          
      - name: Hadolint
        shell: bash -O extglob {0}
        run: |
          sudo wget -qO /usr/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint
          export HADOLINT_NOFAIL=true
          hadolint ${{ env.RELEASE }}/Dockerfile
          
      - name: Echo Release
        shell: bash
        run: |
          echo "RELEASE and TAG"
          echo "Release= ${{ env.RELEASE }}"
          echo "Tag= ${{ env.RELEASETAG }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUN_PASSWORD }}

      - name: Build Multi-Arch
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.RELEASE }}
          file: ${{ env.RELEASE }}/Dockerfile
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            xivastudio/distrobox-${{ env.RELEASE }}:latest
            xivastudio/distrobox-${{ env.RELEASE }}:${{ env.RELEASETAG }}
